#!/bin/bash
set -eu

KEYS_SUBJECT='/C=US/ST=California/L=Mountain View/O=Android/OU=Android/CN=Android/emailAddress=android@android.com'
KEYS_DIR="${HOME}"/.android-certs
mkdir "${KEYS_DIR}"

_keysgen() {
  for cert in bluetooth cyngn-app cyngn-priv-app media networkstack nfc platform releasekey sdk_sandbox shared testcert testkey verity; do
    if [[ ! -f "${KEYS_DIR}"/"${cert}".x509.pem ]]; then
      _make_key "${KEYS_DIR}"/"${cert}" "${KEYS_SUBJECT}"
    fi
  done

  APEX_KEYS=(
    com.android.adbd
    com.android.adservices
    com.android.adservices.api
    com.android.appsearch
    com.android.appsearch.apk
    com.android.art
    com.android.bluetooth
    com.android.bt
    com.android.btservices
    com.android.cellbroadcast
    com.android.compos
    com.android.configinfrastructure
    com.android.connectivity.resources
    com.android.conscrypt
    com.android.crashrecovery
    com.android.devicelock
    com.android.extservices
    com.android.hardware.authsecret
    com.android.hardware.biometrics.face.virtual
    com.android.hardware.biometrics.fingerprint.virtual
    com.android.hardware.boot
    com.android.hardware.cas
    com.android.hardware.contexthub
    com.android.hardware.dumpstate
    com.android.hardware.gatekeeper.nonsecure
    com.android.hardware.neuralnetworks
    com.android.hardware.power
    com.android.hardware.rebootescrow
    com.android.hardware.thermal
    com.android.hardware.threadnetwork
    com.android.hardware.uwb
    com.android.hardware.vibrator
    com.android.hardware.wifi
    com.android.healthfitness
    com.android.hotspot2.osulogin
    com.android.i18n
    com.android.ipsec
    com.android.media
    com.android.media.swcodec
    com.android.mediaprovider
    com.android.nearby.halfsheet
    com.android.networkstack.tethering
    com.android.neuralnetworks
    com.android.nfcservices
    com.android.ondevicepersonalization
    com.android.os.statsd
    com.android.permission
    com.android.profiling
    com.android.resolv
    com.android.rkpd
    com.android.runtime
    com.android.safetycenter.resources
    com.android.scheduling
    com.android.sdkext
    com.android.support.apexer
    com.android.telephony
    com.android.telephonymodules
    com.android.tethering
    com.android.tzdata
    com.android.uprobestats
    com.android.uwb
    com.android.uwb.resources
    com.android.virt
    com.android.vndk.current
    com.android.wifi
    com.android.wifi.dialog
    com.android.wifi.resources
    com.google.pixel.vibrator.hal
    com.qorvo.uwb
  )

  for apex in "${APEX_KEYS[@]}"; do
    if [[ ! -f "${KEYS_DIR}"/"${apex}".x509.pem ]] || [[ ! -f "${KEYS_DIR}"/"${apex}".pem ]] ; then
      subject="${KEYS_SUBJECT//CN=Android/CN=\$\{apex\}}"
      _make_key "${KEYS_DIR}"/"${apex}" "${subject}"
      openssl pkcs8 -in "${KEYS_DIR}"/"${apex}".pk8 -inform DER -nocrypt -out "${KEYS_DIR}"/"${apex}".pem
    fi
  done

  unset KEYS_SUBJECT
}
_keysgen
